//
//  ChecklistDetailsInteractor.swift
//  Ecobalance life
//
//  Created by Artem on 24.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChecklistDetailsBusinessLogic
{
    func doSomething(request: ChecklistDetails.Something.Request)
}

protocol ChecklistDetailsDataStore
{
    //var name: String { get set }
}

class ChecklistDetailsInteractor: ChecklistDetailsBusinessLogic, ChecklistDetailsDataStore
{
    var presenter: ChecklistDetailsPresentationLogic?
    var worker: ChecklistDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ChecklistDetails.Something.Request)
    {
        worker = ChecklistDetailsWorker()
        worker?.doSomeWork()
        
        let response = ChecklistDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
