//
//  RegisterInteractor.swift
//  EcoApp
//
//  Created by Artem on 21.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ParseSwift

protocol RegisterBusinessLogic
{
    func registerUser(with login: String,
                      password: String,
                      cb: @escaping (Result<User, ParseError>) -> Void)
}

protocol RegisterDataStore
{
    //var name: String { get set }
}

class RegisterInteractor: RegisterBusinessLogic, RegisterDataStore
{
    var presenter: RegisterPresentationLogic?
    var worker: RegisterWorker?
    
    func registerUser(with login: String,
                      password: String,
                      cb: @escaping (Result<User, ParseError>) -> Void) {
        User.signup(username: login, password: password) { result in
            cb(result)
        }
    }
    

}
