//
//  RegisterWorker.swift
//  EcoApp
//
//  Created by Artem on 21.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegisterWorker
{
    func doSomeWork()
    {
    }
}
