//
//  TodayPresenter.swift
//  Ecobalance life
//
//  Created by Artem on 20.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodayPresentationLogic
{
    func presentSomething(response: Today.Something.Response)
}

class TodayPresenter: TodayPresentationLogic
{
    weak var viewController: TodayDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Today.Something.Response)
    {
        let viewModel = Today.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
