//
//  TodayWorker.swift
//  Ecobalance life
//
//  Created by Artem on 20.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TodayWorker
{
    func doSomeWork()
    {
    }
}
