//
//  HabitListModels.swift
//  EcoApp
//
//  Created by Artem on 28.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ParseSwift

enum ServerError: Error {
    case parseError(error: ParseError)
    case notConnected
    case ubauthorized
}

enum HabitList
{
    case getHabits(habits: [Habit])
    case likeHabit(habit: Habit)
    case dislikeHabit(habit: Habit)
    case addFact(habit: Habit)
    case getChallenges(challenges: [Challenge])
    
    var requireAuth: Bool {
        switch self {
        case .getHabits, .getChallenges:
            return false
        case .addFact, .dislikeHabit, .likeHabit:
            return true
        }
    }
    
    struct Request {
        var type: HabitList
    }
    struct Response {
        var type: Result<HabitList, ServerError>
    }
    struct ViewModel {
        var type: Result<HabitList, ServerError>
    }
  
}
