//
//  HabitListPresenter.swift
//  EcoApp
//
//  Created by Artem on 28.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HabitListPresentationLogic
{
  func presentSomething(response: HabitList.Something.Response)
}

class HabitListPresenter: HabitListPresentationLogic
{
  weak var viewController: HabitListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: HabitList.Something.Response)
  {
    let viewModel = HabitList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
