//
//  HabitListInteractor.swift
//  EcoApp
//
//  Created by Artem on 28.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HabitListBusinessLogic
{
  func doSomething(request: HabitList.Something.Request)
}

protocol HabitListDataStore
{
  //var name: String { get set }
}

class HabitListInteractor: HabitListBusinessLogic, HabitListDataStore
{
  var presenter: HabitListPresentationLogic?
  var worker: HabitListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HabitList.Something.Request)
  {
    worker = HabitListWorker()
    worker?.doSomeWork()
    
    let response = HabitList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
